### ISSUE TITLE
TypeError: Cannot read property 'default' of undefined

### ISSUE THREAD

**Issue by acuper** [trentm/node-dashdash#11]
Found in latest release 1.9.0, below error is thrown for group options:

```
    {
        group: 'General Options'
    }
```

```
...\node_modules\dashdash\lib\dashdash.js:518
            } else if (optionTypes[o.type].default !== undefined) {
                                          ^
TypeError: Cannot read property 'default' of undefined
    at C:\Users\losadamos\AppData\Roaming\npm\node_modules\bmb.cli\node_modules\dashdash\lib\dashdash.js:518:43
    at Array.forEach (native)
    at Parser.parse (C:\Users\losadamos\AppData\Roaming\npm\node_modules\bmb.cli\node_modules\dashdash\lib\dashdash.js:514:18)
  ...
```

**Comment by trentm** [comment]
Thanks! Another repro:

```
$ node examples/option-groups.js
foo: error: Cannot read property 'default' of undefined
```

**Comment by trentm** [comment]
will be in 1.9.1
