### ISSUE TITLE
Parsing error.

### ISSUE THREAD

**Issue by hshahbodaghkhan** [trentm/node-dashdash#49]
Hello.
when I use the library it give me the following error:

const opts = dashdash.parse({options: options});
                      ^
TypeError: Cannot read property 'parse' of undefined
    at Object.<anonymous> (C:\Users\Hossein\Documents\Automate_Marketing\examples\FirstExperiment.ts:30:23)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Module.m._compile (C:\Users\Hossein\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:836:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\Hossein\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:839:12)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at main (C:\Users\Hossein\AppData\Roaming\npm\node_modules\ts-node\src\bin.ts:226:14)
    at Object.<anonymous> (C:\Users\Hossein\AppData\Roaming\npm\node_modules\ts-node\src\bin.ts:485:3)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

I use the library successfully before.
what is the problem?

**Comment by karfau** [comment]
Your stacktrace tells you that the problem is in your code, not in this library:

```
const opts = dashdash.parse({options: options});
^
TypeError: Cannot read property 'parse' of undefined
at Object. (C:\Users\Hossein\Documents\Automate_Marketing\examples\FirstExperiment.ts:30:23)
```

**Comment by trentm** [comment]
We'd need to see some or all of FirstExperiment.ts to attempt to help. It is possible this has issues with commonjs modules and/or TypeScript usage. I haven't worked with those much.
